apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n-application.fullname" . }}-postgres-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "n8n-application.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
